### PR TITLE
2005 galactica add tests for basefeepergas

### LINKED ISSUE #2005: [Galactica] Add tests for baseFeePerGas
### Description

for `baseFeePerGas` in block, we could add solo tests:
- thorClient in network --> check value is hex number
- RPC layer, for example `eth_getBlockByNumber` to also check field exists and is hex number

### Reproduction URL

_No response_

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash

```

### OS

_No response_

### PR DESCRIPTION
**Pull request by lucanicoladebiasi**
# Description

Validate the additional fields introduced to support **galactica** compatibility.

Fixes #2005

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change required a documentation update.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test `yarn test:examples`
- [x] Test `yarn test:solo`
- [x] Test `yarn test:unit`

**Test Configuration**:
* Node.js Version: v23.11.0
* Yarn Version: 1.22.22

### CODE REVIEW

**Comment by lucanicoladebiasi** [comment]
The interfaces
- `packages/network/src/provider/utils/formatter/blocks/types.d.ts!BlockHeadRPC` 
    - moves `baseFeePerGas` to supported fields; 
- `packages/network/src/provider/utils/formatter/transactions/types.d.ts!TransactionRPC`
    - moves `type`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas` to supported fields.

File: packages/network/src/provider/utils/formatter/blocks/formatter.ts [hunk 1]
```diff
@@ -45,6 +45,7 @@ const formatToRPCStandard = (
         gasUsed: Quantity.of(block.gasUsed).toString(),
         transactions,
         miner: block.beneficiary,
+        baseFeePerGas: block.baseFeePerGas ?? '0x0',
```
Comment (victhorbi) [inline packages/network/src/provider/utils/formatter/blocks/formatter.ts:48]: We shouldn't default this to any value for older (before Galactica) blocks

Comment (lucanicoladebiasi) [reply packages/network/src/provider/utils/formatter/blocks/formatter.ts:48]: Before the change I introduced, the `baseFeePerGas` existed among Unsupported fields (below line 50), always set equal `0x0`, hence I do believe what I did is right because when `block.baseFeePerGas` is missing, the code behaves like before.
Please, can you check if I'm right or else.

Comment (lucanicoladebiasi) [reply packages/network/src/provider/utils/formatter/blocks/formatter.ts]: I clarified the issue `0x0` vs `undefined` with @claytonneal. The correct and wanted behavior is to

File: packages/network/src/provider/utils/formatter/transactions/types.d.ts [hunk 2]
```diff
@@ -51,14 +51,26 @@ interface TransactionRPC {
      */
     nonce: string;
 
+    /**
+     * The transaction type in number, currently 0(Legacy Transaction) and 81(DynamicFee Transaction) are supported.
```
Comment (claytonneal) [inline packages/network/src/provider/utils/formatter/transactions/types.d.ts:55]: The comment here is vechain (81), but in ethereum is 0 and 2 ?

**Review by claytonneal — CHANGES_REQUESTED** [review]

File: packages/network/src/provider/utils/formatter/blocks/formatter.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (lucanicoladebiasi) [reply packages/network/src/provider/utils/formatter/blocks/formatter.ts]: Yes. Done.

File: packages/network/src/provider/utils/formatter/blocks/types.d.ts [hunk 3]
```diff
@@ -80,13 +80,17 @@ interface BlocksRPC extends BlockHeaderRPC {
      */
     transactions: string[] | TransactionRPC[];
 
+    /**
+     * The base fee value.
+     */
+    baseFeePerGas: string;
```
[the remark this answers is not in the document]
Comment (lucanicoladebiasi) [reply packages/network/src/provider/utils/formatter/blocks/types.d.ts]: Agreed. Done.

File: packages/network/tests/provider/rpc-mapper/methods/eth_getBlockByNumber/eth_getBlockByNumber.solo.test.ts [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+        thorClient = new ThorClient(new SimpleHttpClient(THOR_SOLO_URL), {
+            isPollingEnabled: true
+        });
+    });
+
+    afterEach(() => {
+        thorClient.destroy();
+    });
+
+    describe('GALACTICA - baseFeePerGas', () => {
```
[the remark this answers is not in the document]
Comment (lucanicoladebiasi) [reply packages/network/tests/provider/rpc-mapper/methods/eth_getBlockByNumber/eth_getBlockByNumber.solo.test.ts:34]: Tests added.

File: packages/network/src/provider/utils/formatter/transactions/types.d.ts (hunk 2 above)
Comment (lucanicoladebiasi) [reply packages/network/src/provider/utils/formatter/transactions/types.d.ts:55]: Yes. My understanding is Thor Galactica sets transaction type = 81 where Ethereum London sets transaction type = 2 for EIP-1559 implementation.

**Review by GrandinLuc — APPROVED** [review]
All good, just a question: aren't private keys written as hex string usually written without the 0x at the front ?

**Review by claytonneal — APPROVED** [review]
thanks
